# Se necesita docker y docker-compose. Ejecutar con:
# docker-compose -f docker-compose.yml up
# Se iniciará un contenedor con postgresql y otro con odoo. 
# Para evitar conflictos con el puerto en local si ya hay postgres
# se usa el 5433 en lugar del estándar 5432 de postgresql.
---
version: '3.7'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    image: postgres:9.6
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - data_storage:/var/lib/postgresql/data
  odoo12:
    container_name: odoo12
    depends_on:
      - db
    image: "rubencabrera/odoo-docker:12.12.3"
    ports: 
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    restart: always
    volumes:
      - odoo_data:/var/lib/odoo
volumes:
  # TODO: The local paths need to exist for volumes to be mounted
  data_storage:
  odoo_data:
